platform :android do
  lane :deploy do
    flutter(args: ["build", "appbundle"])

    upload_to_play_store(
      aab: "../../build/app/outputs/bundle/release/app-release.aab",
      json_key: "./google_play_api_key.json"
    )
  end
end

